thread_event: thread_event.cpp
	g++ $^ -o $@.exe
thread_event2: thread_event2.cpp
	g++ $^ -o $@.exe
thread_mutex: thread_mutex.cpp
	$(warning Please compiles this program under 'Developer Command Prompt for VS')
	cl  $^ -o $@.exe
clean:
	rm -f *.exe *.obj
